version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/api/health || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - portfolio-network

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000/api
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_KEY_TZ=${VITE_API_KEY_TZ}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
