
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT:-5174}:5174"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_KEY_TZ=${VITE_API_KEY_TZ}
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development